# This file configures logchange tool ðŸŒ³ ðŸª“ => ðŸªµ 
# Visit https://github.com/logchange/logchange and leave a star ðŸŒŸ 
# More info about configuration you can find https://github.com/logchange/logchange#configuration 
changelog:
  heading: ""
  labels:
    unreleased: unreleased
    important_notes: Important notes
    types:
      added: Added
      changed: Changed
      deprecated: Deprecated
      removed: Removed
      fixed: Fixed
      security: Security
      dependency_update: Dependency updates
      other: Security
      number_of_changes:
        singular: change
        plural: changes
    configuration:
      heading: Configuration changes
      type: Type
      actions:
        add: Added
        update: Updated
        delete: Deleted
      with_default_value: with default value
      description: Description
  templates:
    entry: "${prefix}${title} ${merge_requests} ${issues} ${links} ${authors}"
