title: Changed YAML keyword `configuration` to `configurations`
authors:
  - name: Peter
    nick: marwin1991
    url: https://github.com/marwin1991
type: changed # [added/changed/deprecated/removed/fixed/security/other]

