title: Added ability to configure CHANGELOG labels via `logchange-config.yml`.
authors:
  - name: Peter
    nick: marwin1991
    url: https://github.com/marwin1991
type: added # [added/changed/deprecated/removed/fixed/security/other]

