title: Fixed duplicated config entries, when more than one type specified, special thanks to @Riserax
authors:
  - name: Peter
    nick: marwin1991
    url: https://github.com/marwin1991
type: fixed # [added/changed/deprecated/removed/fixed/security/dependency_update/other]
issues:
  - 64
merge_requests:
  - 68
