name: Update distributions

on:
  release:
    types: [released]

jobs:
  update-distributions:
    name: Update homebrew tap formula
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download .zip assets from latest release
        run: |
          gh release download --pattern "*.zip" --dir ./bins
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update distributions
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.LOGCHANGE_PAT_TOKEN }}