# This file is used by logchange tool to generate CHANGELOG.md ğŸŒ³ ğŸª“ => ğŸªµ
# Visit https://github.com/logchange/logchange and leave a star ğŸŒŸ
# More info about configuration you can find https://github.com/logchange/logchange#yaml-format â¬…ï¸â¬… ï¸
title: Added ability to configure the entry format in the Changelog.md file.
authors:
  - name: Mateusz Witkowski
    nick: witx98
    url: https://github.com/witx98
issues:
  - 338
merge_requests:
  - 351
type: added # [added/changed/deprecated/removed/fixed/security/dependency_update/other]
